version: '3.8'

services:
  db:
    image: mysql
    container_name: jdbc_project
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOTPASSWORD: ${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE: ${DB_DATABASE}